name: ci

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}
    - name: Install gem dependencies
      run: bundle install --path vendor/bundle --deployment --without production staging development
    - name: Run Rubocop
      run: bundle exec rubocop
    - name: Run Rspec
      run: bundle exec rspec
    - uses: actions/upload-artifact@v2
      with:
        name: coverage_rspec
        path: coverage
