name: deploy-to-staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}

      - name: bundle config
        run: |
          bundle config set path 'vendor/bundle'
          bundle config set deployment 'true'
          bundle config set without 'development test'

      - name: bundle install
        run: |
          cd src
          bundle install

      - name: create lambda package
        run: |
          cd src
          zip -r ../package.zip .

      # see: https://github.com/aws-actions/configure-aws-credentials
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # lambda-template-for-ruby-staging
      # see: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/list-functions.html
      - name: check lambda function exists
        id: function_exists
        run: |
          aws lambda list-functions \
            | grep "\"FunctionName\": \"lambda-template-for-ruby-staging\""
        continue-on-error: true

      # see: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/create-function.html
      - name: deploy to lambda (create)
        run: |
          aws lambda create-function \
            --function-name lambda-template-for-ruby-staging \
            --runtime ruby2.7 \
            --handler main.lambda_handler \
            --role ${{ secrets.AWS_LAMBDA_ROLE_ARN_STAGING }} \
            --zip-file fileb://package.zip \
            --environment "Variables={APP_ENV=staging}" \
            --publish
        if: steps.function_exists.outcome == 'failure'

      # see: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/update-function-code.html
      - name: deploy to lambda (update)
        run: |
          aws lambda update-function-code \
            --function-name lambda-template-for-ruby-staging \
            --zip-file fileb://package.zip \
            --publish
        if: steps.function_exists.outcome == 'success'

