name: deploy-to-staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION:           ap-northeast-1
      LAMBDA_FUNCTION_NAME: function-staging
      AWS_LAMBDA_ROLE_ARN:  ${{ secrets.AWS_LAMBDA_ROLE_ARN_STAGING }}
      APP_ENV:              staging

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # Copy from deploy-to-production.yml
